# Generated by Django 3.0.4 on 2020-03-17 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("modeanalytics", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="AppReportModel",
            fields=[
                (
                    "modereportmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="modeanalytics.ModeReportModel",
                    ),
                ),
                ("app_name", models.CharField(max_length=10)),
            ],
            options={"verbose_name": "App Reports", "db_table": "app_report"},
            bases=("modeanalytics.modereportmodel",),
        )
    ]
