# Generated by Django 3.0.4 on 2020-03-17 20:13

from typing import List

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

import modeanalytics.models


class Migration(migrations.Migration):

    initial = True

    dependencies: List[str] = []

    operations = [
        migrations.CreateModel(
            name="ModeReportModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="Report Name")),
                ("run_token", models.CharField(max_length=16, verbose_name="Run Token")),
                ("space", models.CharField(blank=True, max_length=16, null=True, verbose_name="Space")),
                (
                    "params",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=modeanalytics.models.f, verbose_name="Query Parameters(JSON)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={"verbose_name": "Report", "db_table": "report", "ordering": ("pk",)},
        )
    ]
