# Generated by Django 3.0.4 on 2020-03-17 21:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import modeanalytics.models


class Migration(migrations.Migration):

    dependencies = [("modeanalytics", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="modereportmodel",
            name="params",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=modeanalytics.models.f, null=True, verbose_name="Query Parameters(JSON)"
            ),
        )
    ]
